### ISSUE TITLE
Error collecting Trino metrics

### ISSUE THREAD

**Issue by denerops** [aws-samples/emr-trino-autoscale#3]
```
Error collecting Trino metrics
Apr 16 14:50:50 cluster.domain.example.br trino-autoscale[16540]: javax.management.InstanceNotFoundException: trino.memory:name=ClusterMemoryManager
Apr 16 14:50:50 cluster.domain.example.br trino-autoscale[16540]:         at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getMBean(DefaultMBeanServerInterceptor.java:1088)
Apr 16 14:50:50 cluster.domain.example.br trino-autoscale[16540]:         at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getAttribute(DefaultMBeanServerInterceptor.java:640)
Apr 16 14:50:50 cluster.domain.example.br trino-autoscale[16540]:         at com.sun.jmx.mbeanserver.JmxMBeanServer.getAttribute(JmxMBeanServer.java:679)
Apr 16 14:50:50 cluster.domain.example.br trino-autoscale[16540]:         at javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1449)
Apr 16 14:50:50 cluster.domain.example.br trino-autoscale[16540]:         at javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1310)
Apr 16 14:50:50 cluster.domain.example.br trino-autoscale[16540]:         at javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1405)
Apr 16 14:50:50 cluster.domain.example.br trino-autoscale[16540]:         at javax.management.remote.rmi.RMIConnectionImpl.getAttribute(RMIConnectionImpl.java:639)
Apr 16 14:50:50 cluster.domain.example.br trino-autoscale[16540]:         at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Apr 16 14:50:50 cluster.domain.example.br trino-autoscale[16540]:         at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
Apr 16 14:50:50 cluster.domain.example.br trino-autoscale[16540]:         at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Apr 16 14:50:50 cluster.domain.example.br trino-autoscale[16540]:         at java.lang.reflect.Method.invoke(Method.java:568)
Apr 16 14:50:50 cluster.domain.example.br trino-autoscale[16540]:         at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:360)
Apr 16 14:50:50 cluster.domain.example.br trino-autoscale[16540]:         at sun.rmi.transport.Transport$1.run(Transport.java:200)
Apr 16 14:50:50 cluster.domain.example.br trino-autoscale[16540]:         at sun.rmi.transport.Transport$1.run(Transport.java:197)
Apr 16 14:50:50 cluster.domain.example.br trino-autoscale[16540]:         at java.security.AccessController.doPrivileged(AccessController.java:712)
Apr 16 14:50:50 cluster.domain.example.br trino-autoscale[16540]:         at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
Apr 16 14:50:50 cluster.domain.example.br trino-autoscale[16540]:         at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:587)
Apr 16 14:50:50 cluster.domain.example.br trino-autoscale[16540]:         at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:828)
Apr 16 14:50:50 cluster.domain.example.br trino-autoscale[16540]:         at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:705)
Apr 16 14:50:50 cluster.domain.example.br trino-autoscale[16540]:         at java.security.AccessController.doPrivileged(AccessController.java:399)
Apr 16 14:50:50 cluster.domain.example.br trino-autoscale[16540]:         at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:704)
Apr 16 14:50:50 cluster.domain.example.br trino-autoscale[16540]:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
Apr 16 14:50:50 cluster.domain.example.br trino-autoscale[16540]:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
Apr 16 14:50:50 cluster.domain.example.br trino-autoscale[16540]:         at java.lang.Thread.run(Thread.java:840)
Apr 16 14:50:50 cluster.domain.example.br trino-autoscale[16540]:         at sun.rmi.transport.StreamRemoteCall.exceptionReceivedFromServer(StreamRemoteCall.java:303)
Apr 16 14:50:50 cluster.domain.example.br trino-autoscale[16540]:         at sun.rmi.transport.StreamRemoteCall.executeCall(StreamRemoteCall.java:279)
Apr 16 14:50:50 cluster.domain.example.br trino-autoscale[16540]:         at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:164)
Apr 16 14:50:50 cluster.domain.example.br trino-autoscale[16540]:         at com.sun.jmx.remote.internal.PRef.invoke(Unknown Source)
Apr 16 14:50:50 cluster.domain.example.br trino-autoscale[16540]:         at javax.management.remote.rmi.RMIConnectionImpl_Stub.getAttribute(Unknown Source)
Apr 16 14:50:50 cluster.domain.example.br trino-autoscale[16540]:         at javax.management.remote.rmi.RMIConnector$RemoteMBeanServerConnection.getAttribute(RMIConnector.java:903)
Apr 16 14:50:50 cluster.domain.example.br trino-autoscale[16540]:         at com.amazonaws.emr.metrics.TrinoJmxEmr.getRemoteAttribute(TrinoJmxEmr.scala:36)
Apr 16 14:50:50 cluster.domain.example.br trino-autoscale[16540]:         at com.amazonaws.emr.metrics.TrinoJmxEmr.getAttribute(TrinoJmxEmr.scala:33)
Apr 16 14:50:50 cluster.domain.example.br trino-autoscale[16540]:         at com.amazonaws.emr.metrics.TrinoJmxEmr.$anonfun$getClusterMemory$1(TrinoJmxEmr.scala:44)
Apr 16 14:50:50 cluster.domain.example.br trino-autoscale[16540]:         at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
Apr 16 14:50:50 cluster.domain.example.br trino-autoscale[16540]:         at scala.util.Success.$anonfun$map$1(Try.scala:255)
Apr 16 14:50:50 cluster.domain.example.br trino-autoscale[16540]:         at scala.util.Success.map(Try.scala:213)
Apr 16 14:50:50 cluster.domain.example.br trino-autoscale[16540]:         at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
Apr 16 14:50:50 cluster.domain.example.br trino-autoscale[16540]:         at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
Apr 16 14:50:50 cluster.domain.example.br trino-autoscale[16540]:         at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
```

**Comment by ripani-aws** [comment]
Hi @denerops, apologies for the delay but the notifications were not routed to the correct email address. From the exception, it looks that the coordinator is not exposing the Cluster Memory MBean. Which version of EMR are you using? Also is this a transient or repetitive error?

**Comment by ripani-aws** [comment]
Closing due to inactivity.
